version: '3.1'

services:
  db:
    container_name: aperture
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: 'admin'
    volumes:
      - ./src/db:/db-scripts/